version: 1.0.{build}
build_script:
- ps: ./build.ps1 -t Ci
artifacts:
- path: '*.nupkg'
  name: NugetPackage
deploy:
- provider: NuGet
  api_key:
    secure: xsWQxSQvBPZpKooeSJ0u79hcwoP0G0A4B4Xm3aXIvHhdW+UsuCL+3g+Z5u0JH1fA
  artifact: /.*\.nupkg/